import RootDashboard from '@/components/dashboard/root-dashboard';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Dashboard | Hr Management - Web Briks LLC',
    description: 'Generated by create next app',
};

export default function Dashboard() {
    return <RootDashboard />;
}
