export const BANGLADESH_BANKS = [
    "Dutch-Bangla Bank Limited",
    "BRAC Bank Limited",
    "City Bank Limited",
    "Islami Bank Bangladesh Limited",
    "Sonali Bank Limited",
    "Agrani Bank Limited",
    "Janata Bank Limited",
    "Rupali Bank Limited",
    "Prime Bank Limited",
    "Mutual Trust Bank Limited",
    "Mercantile Bank Limited",
    "Eastern Bank Limited",
    "Pubali Bank Limited",
    "United Commercial Bank Limited",
    "Standard Chartered Bank",
    "HSBC",
    "Trust Bank Limited",
    "Bank Asia Limited",
    "Dhaka Bank Limited",
    "National Bank Limited",
];
