import RootAccount from '@/components/account/account';
import { Spinner } from '@/components/ui/spinner';
import { Metadata } from 'next';
import { Suspense } from 'react';

export const metadata: Metadata = {
    title: 'Account | Hr Management - Web Briks LLC',
    description: 'Generated by create next app',
};

export default function Account() {
    return (
        <Suspense
            fallback={
                <div className="h-full w-full flex items-center justify-center">
                    <Spinner />
                </div>
            }
        >
            <RootAccount />
        </Suspense>
    );
}
