import { Metadata } from 'next';
import { ReactNode } from 'react';

export const metadata: Metadata = {
    title: 'Auth | Hr Management - Web Briks LLC',
    description: 'Generated by create next app',
};

export default function AuthLayout({ children }: { children: ReactNode }) {
    return children;
}
