import SignupForm from '@/components/auth/sign-up';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Sign Up | Hr Management - Web Briks LLC',
    description: 'Generated by create next app',
};

export default function SignupPage() {
    return (
        <section className="flex min-h-svh w-full items-center justify-center p-6 md:p-10">
            <div className="w-full max-w-md">
                <SignupForm />
            </div>
        </section>
    );
}
